Puppet::Type.type(:network_config).provide(:network_scripts) do
  desc "Provider for configuration of network_scripts"

  defaultfor :operatingsystem => [:redhat, :fedora, :centos]

  has_features :manages_userctl

  # checks for network-script existence and correctness
  def exists?
    @config_file = "/etc/sysconfig/network-scripts/ifcfg-#{@resource[:name]}"

    # do not check file contents if the purpose is to ensure the file isn't there
    return File.exists?(@config_file) if @resource[:ensure] == :absent

    # load puppet configuration (`should`)
    @memory_values = {}

    # Get any property set in the resource that isn't a metaparameter
    mp = Puppet::Type::metaparams << :ensure << :provider
    @resource.to_hash.delete_if { |k,v| mp.include? k }.each_pair { |k, v|
      @memory_values[k.to_s.upcase.to_sym] = v.to_s unless v.nil?
    }

    # load on-disk configuration (`is`)
    @disk_values = load_disk_config()

    return @disk_values == @memory_values
  end

  def create
    File.open(@config_file.to_s, 'w') do |f|
      f.write("# Generated by puppet-network on #{Time.now.strftime("%F %T")}\n")
      @memory_values.each_pair do |k, v|
        # only quote values that include the space character
        vs = v.nil? ? k : v.include?(' ') ? "#{k}=\"#{v}\"" : "#{k}=#{v}"
        f.write("#{vs}\n")
      end
    end
  end

  def destroy
    if File.exists?(@config_file)
      Puppet.notice "Destroying #{@config_file}"
      File.unlink(@config_file)
    end
  end

  # Reads the content in the config file and returns a hash of keys & values
  def load_disk_config
    return nil unless File.exists?(@config_file)

    config_hash = {}

    File.readlines(@config_file).each do |line|
      next unless line =~ /^\s*([A-Za-z][^=]+)="?([^"]+)"?$/
      config_hash[$1.strip.upcase.to_sym] = $2.strip
    end

    Puppet.debug "Loaded file: #{@config_file}"
    return config_hash
  end
end
